// GENERATED by `python -m orbit.params --emit-vh` from orbit/params.py. Do not edit.
// tools/params_check.py fails if this file differs from what params.py generates.
// Macros rather than localparams because Verilog-2001 has no compilation-unit
// scope parameters, and module parameter defaults may only reference macros.
`ifndef ORBIT_PARAMS_VH
`define ORBIT_PARAMS_VH

// --- frames ---
`define ORBIT_FRAME_W                128
`define ORBIT_FRAME_H                128
`define ORBIT_FRAME_BYTES            16384
`define ORBIT_PIXELS_PER_CYCLE       8
`define ORBIT_QUEUE_DEPTH            32

// --- scoring defaults ---
`define ORBIT_CLOUD_THRESHOLD        200
`define ORBIT_CHANGE_THRESHOLD       16
`define ORBIT_SHARP_SHIFT            5
`define ORBIT_SHARP_SHIFT_MAX        24
`define ORBIT_W_CLEAR                21845
`define ORBIT_W_SHARP                21845
`define ORBIT_W_CHANGE               21845

// --- link ---
`define ORBIT_CLK_HZ                 100000000
`define ORBIT_BAUD                   115200
`define ORBIT_HEARTBEAT_MS           1000
`define ORBIT_LINK_TIMEOUT_MS        3000
`define ORBIT_POWER_PERIOD_MS        250
`define ORBIT_ORCH_ID                255
`define ORBIT_MAX_FRAME              253
`define ORBIT_TX_FIFO_FRAMES         64

// --- INA219 ---
`define ORBIT_INA219_ADDR            64

`endif
