"""Single source of truth for every constant. rtl/orbit_params.vh is GENERATED
from HW_PARAMS below (`python -m orbit.params --emit-vh`); tools/params_check.py
fails if the committed header differs from what this file generates.
No magic numbers anywhere else."""
import sys

# --- frames --------------------------------------------------------------------
FRAME_W = 128
FRAME_H = 128
FRAME_BYTES = FRAME_W * FRAME_H          # 16384: 8-bit grayscale, one byte per pixel
PIXELS_PER_CYCLE = 8                     # kernel width; frame/ref BRAM words are PIXELS_PER_CYCLE*8 bits
QUEUE_DEPTH = 32                         # priority-queue cells; runtime limit <= this via CONFIG_SET

# --- scoring defaults (power-on values in the RTL; runtime-writable via CONFIG_SET) ----
CLOUD_THRESHOLD = 200                    # pixel > this counts as cloud (8-bit brightness)
CHANGE_THRESHOLD = 16                    # |pixel - ref| > this counts as changed
SHARP_SHIFT = 5                          # sharp_u16 = sat16(sobel_sum >> SHARP_SHIFT); tuned at the corpus gate
W_CLEAR = 21845                          # u16 weights; score = sat16((w.m summed) >> 16)
W_SHARP = 21845
W_CHANGE = 21845
SHARP_SHIFT_MAX = 24                     # CONFIG_SET rejects larger shifts (sum < 2^25, so 24 already floors it)

# --- contact window (ground model; scaled for the demo at the corpus gate, labelled as such) ---
WINDOW_DURATION_S = 600
LINK_RATE_BPS = 10_000_000
STARVATION_N = 2                         # consecutive grants to one node before a forced switch

# --- link ----------------------------------------------------------------------
CLK_HZ = 100_000_000
BAUD = 115200
HEARTBEAT_MS = 1000
LINK_TIMEOUT_MS = 3000
POWER_PERIOD_MS = 250
ORCH_ID = 0xFF
MAX_FRAME = 253             # bytes pre-COBS; 254 non-zero bytes would force a 0xFF code block (two overhead bytes)
TX_FIFO_FRAMES = 64

# --- INA219 --------------------------------------------------------------------
INA219_ADDR = 0x40
INA219_SHUNT_OHM = 0.1
INA219_BUS_LSB_V = 0.004    # bus register: (raw >> 3) * 4 mV
INA219_SHUNT_LSB_V = 10e-6  # shunt register: raw * 10 uV

# --- deployment -----------------------------------------------------------------
# Transport chosen by path scheme, nothing else changes:
#   sim://<n>            SimulatedNode (golden model in-process)
#   verilator://<n>      VerilatorNode (compiled RTL, UART over a pty)
#   /dev/tty.usbserial-* HardwareNode  (pyserial to an Arty)
NODES = ["sim://0", "sim://1"]

# --- what the RTL sees -----------------------------------------------------------
# (group comment, [names]); every name must be an int above. Ground-only values
# (window, starvation, INA219 conversion) are deliberately absent.
HW_PARAMS = [
    ("frames", ["FRAME_W", "FRAME_H", "FRAME_BYTES", "PIXELS_PER_CYCLE", "QUEUE_DEPTH"]),
    ("scoring defaults", ["CLOUD_THRESHOLD", "CHANGE_THRESHOLD", "SHARP_SHIFT", "SHARP_SHIFT_MAX",
                          "W_CLEAR", "W_SHARP", "W_CHANGE"]),
    ("link", ["CLK_HZ", "BAUD", "HEARTBEAT_MS", "LINK_TIMEOUT_MS", "POWER_PERIOD_MS", "ORCH_ID",
              "MAX_FRAME", "TX_FIFO_FRAMES"]),
    ("INA219", ["INA219_ADDR"]),
]


def emit_vh() -> str:
    g = globals()
    lines = ["// GENERATED by `python -m orbit.params --emit-vh` from orbit/params.py. Do not edit.",
             "// tools/params_check.py fails if this file differs from what params.py generates.",
             "// Macros rather than localparams because Verilog-2001 has no compilation-unit",
             "// scope parameters, and module parameter defaults may only reference macros.",
             "`ifndef ORBIT_PARAMS_VH", "`define ORBIT_PARAMS_VH", ""]
    for group, names in HW_PARAMS:
        lines.append(f"// --- {group} ---")
        for n in names:
            v = g[n]
            assert isinstance(v, int) and v >= 0, n
            lines.append(f"`define ORBIT_{n:<22} {v}")
        lines.append("")
    lines += ["`endif", ""]
    return "\n".join(lines)


if __name__ == "__main__":
    if sys.argv[1:] == ["--emit-vh"]:
        from pathlib import Path
        out = Path(__file__).resolve().parent.parent / "rtl" / "orbit_params.vh"
        out.write_text(emit_vh())
        print("wrote", out)
    else:
        print(emit_vh(), end="")
