"""One frame through the kernel with every intermediate a human can check by hand:
a 3x3 window's Sobel taps, the three counts, the normalisations and the composite,
then the same frame through a 4-cell queue. Emits docs/worked_example.md
(`python -m orbit.golden.worked_example --md docs/worked_example.md`); a test pins
that file to this code."""
from __future__ import annotations

import sys

import numpy as np

from orbit import params
from .queue import NO_FRAME, PriorityQueue
from .score import Config, score_frame, score_frame_ref

H, W = params.FRAME_H, params.FRAME_W


def example_frame() -> tuple[np.ndarray, np.ndarray]:
    """Deterministic, structured, small numbers: a dark field with a bright 'cloud' block
    in the top-left quarter, a diagonal edge, and a reference that differs in one band."""
    y, x = np.indices((H, W))
    frame = (40 + (x // 8) * 3).astype(np.int32)              # gentle horizontal ramp, 40..87
    frame[y + x > 160] += 60                                    # diagonal edge, +60
    frame[(y < 64) & (x < 64)] = 230                            # cloud block above CLOUD_THRESHOLD
    ref = frame.copy()
    ref[96:112, :] = 0                                          # a band the reference lacks
    return frame.clip(0, 255).astype(np.uint8), ref.clip(0, 255).astype(np.uint8)


def render(md: bool = False) -> str:
    cfg = Config()
    frame, ref = example_frame()
    s = score_frame(frame, ref, cfg)
    assert s == score_frame_ref(frame, ref, cfg)
    o = []
    p = o.append
    p("# Worked example — one frame through the scoring kernel (protocol.md §5.2)")
    p("")
    p("Generated by `python -m orbit.golden.worked_example --md`; `tests/test_golden.py` pins it.")
    p("Frame: 128×128, a 40..87 ramp, +60 beyond the diagonal y+x>160, a 230-valued 64×64 block")
    p("top-left (cloud). Reference: the same frame with rows 96..111 set to 0.")
    p("")
    p(f"Config: w_clear={cfg.w_clear} w_sharp={cfg.w_sharp} w_change={cfg.w_change} "
      f"cloud_thr={cfg.cloud_thr} change_thr={cfg.change_thr} sharp_shift={cfg.sharp_shift}")
    p("")
    p("## One 3×3 window, at the diagonal edge (y=100, x=61)")
    y0, x0 = 100, 61
    win = frame[y0 - 1:y0 + 2, x0 - 1:x0 + 2].astype(int)
    p("```")
    for row in win:
        p("  " + " ".join(f"{v:3d}" for v in row))
    gx = (win[0, 2] - win[0, 0]) + 2 * (win[1, 2] - win[1, 0]) + (win[2, 2] - win[2, 0])
    gy = (win[2, 0] - win[0, 0]) + 2 * (win[2, 1] - win[0, 1]) + (win[2, 2] - win[0, 2])
    p(f"Gx = ({win[0,2]}−{win[0,0]}) + 2·({win[1,2]}−{win[1,0]}) + ({win[2,2]}−{win[2,0]}) = {gx}")
    p(f"Gy = ({win[2,0]}−{win[0,0]}) + 2·({win[2,1]}−{win[0,1]}) + ({win[2,2]}−{win[0,2]}) = {gy}")
    p(f"|Gx|+|Gy| = {abs(gx) + abs(gy)}   (this window's contribution to sobel_sum)")
    p("```")
    p("")
    p("## Whole-frame counts")
    p("```")
    p(f"cloud_px   = #(p > {cfg.cloud_thr})          = {s.cloud_px}   (the 64×64 block = 4096)")
    p(f"changed_px = #(|p − ref| > {cfg.change_thr})   = {s.changed_px}   (16 rows × 128 = 2048 where ref is 0)")
    p(f"sobel_sum  = Σ|Gx|+|Gy| interior = {s.sobel_sum}")
    p("```")
    p("")
    p("## Normalise and combine")
    p("```")
    p(f"clear  = sat16((16384 − {s.cloud_px}) << 2) = sat16({(16384 - s.cloud_px) << 2}) = {s.clear}")
    p(f"sharp  = sat16({s.sobel_sum} >> {cfg.sharp_shift}) = sat16({s.sobel_sum >> cfg.sharp_shift}) = {s.sharp}")
    p(f"change = sat16({s.changed_px} << 2) = sat16({s.changed_px << 2}) = {s.change}")
    acc = cfg.w_clear * s.clear + cfg.w_sharp * s.sharp + cfg.w_change * s.change
    p(f"score  = sat16(({cfg.w_clear}·{s.clear} + {cfg.w_sharp}·{s.sharp} + {cfg.w_change}·{s.change}) >> 16)")
    p(f"       = sat16({acc} >> 16) = sat16({acc >> 16}) = {s.score}   → displayed {s.score * 100 / 65535:.1f}/100")
    p("```")
    p("")
    p("## Queue of 4 cells (protocol.md §5.3)")
    q = PriorityQueue(4)
    p("```")
    for score, fid in [(s.score, 1), (30000, 2), (s.score, 3), (10, 4), (5, 5), (60000, 6)]:
        lost = q.insert(score, fid)
        p(f"insert score={score:5d} id={fid}  → cells={[(a, b) for a, b in q.cells]}"
          f"  lost={'none' if lost == NO_FRAME else lost}")
    top = q.pop()
    p(f"pop → {top}; new top = {q.top}; frames_evicted = {q.evicted}")
    p("```")
    return "\n".join(o) + "\n"


def main(argv=None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    text = render()
    if len(argv) == 2 and argv[0] == "--md":
        with open(argv[1], "w") as f:
            f.write(text)
        print("wrote", argv[1])
    else:
        print(text, end="")
    return 0


if __name__ == "__main__":
    sys.exit(main())
